[package]
name = "merkle_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
hex = "0.4.3"
sha2  = "0.10.0"